# Generated by Django 3.1.2 on 2020-11-17 17:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(default=None, max_length=20, verbose_name='Номер телефона')),
                ('group', models.CharField(default='User', max_length=20, verbose_name='Группа')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProfileAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(blank=True, default=None, max_length=20, null=True, verbose_name='Страна')),
                ('city', models.CharField(blank=True, default=None, max_length=20, null=True, verbose_name='Город')),
                ('index', models.CharField(blank=True, default=None, max_length=15, null=True, verbose_name='Индекс')),
                ('address1', models.CharField(blank=True, default=None, max_length=50, null=True, verbose_name='Адрес1')),
                ('address2', models.CharField(blank=True, default=None, max_length=50, null=True, verbose_name='Адрес2')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='profile_address', to='myauth.profile')),
            ],
        ),
    ]
