# Generated by Django 3.1.2 on 2020-11-18 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myauth', '0002_auto_20201118_1209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profileaddress',
            name='address1',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Адрес1'),
        ),
        migrations.AlterField(
            model_name='profileaddress',
            name='address2',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Адрес2'),
        ),
        migrations.AlterField(
            model_name='profileaddress',
            name='city',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Город'),
        ),
        migrations.AlterField(
            model_name='profileaddress',
            name='country',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Страна'),
        ),
        migrations.AlterField(
            model_name='profileaddress',
            name='index',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Индекс'),
        ),
    ]
