# Generated by Django 3.1.2 on 2020-11-23 21:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myauth', '0004_profile_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditCart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(blank=True, null=True, verbose_name='Номер карты')),
                ('data_cart', models.CharField(blank=True, max_length=5, null=True, verbose_name='Дата карты')),
                ('name', models.CharField(blank=True, max_length=30, null=True, verbose_name='Имя пользователя')),
                ('cvv', models.PositiveIntegerField(blank=True, null=True, verbose_name='CVV')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='credit_cards', to='myauth.profile')),
            ],
            options={
                'verbose_name': 'Банковская карта',
                'verbose_name_plural': 'Банковские карты',
            },
        ),
    ]
