# Generated by Django 3.1.2 on 2020-12-02 06:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cart', '0005_cart_coupon_percent'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=9, verbose_name='Название купона')),
                ('percent', models.PositiveIntegerField(verbose_name='Процент скидки %')),
                ('active', models.BooleanField(default=True, verbose_name='Активный (Да/Нет)')),
                ('date_add', models.DateTimeField(auto_now_add=True, verbose_name='Дата внесения в каталог')),
                ('date_last_change', models.DateTimeField(auto_now=True, verbose_name='Дата последнего изменения карточки')),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='coupons', to='cart.cart')),
            ],
        ),
    ]
