# Generated by Django 3.1.2 on 2020-10-19 21:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('references', '0004_publisher'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='active',
            field=models.BooleanField(verbose_name='Активный (доступен для заказа, Да/Нет)'),
        ),
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.ManyToManyField(to='references.Author', verbose_name='Авторы книги'),
        ),
        migrations.AlterField(
            model_name='book',
            name='date_add',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата внесения в каталог'),
        ),
        migrations.AlterField(
            model_name='book',
            name='date_last_change',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата последнего изменения карточки'),
        ),
        migrations.AlterField(
            model_name='book',
            name='genre',
            field=models.ManyToManyField(to='references.Genre', verbose_name='Жанры'),
        ),
        migrations.AlterField(
            model_name='book',
            name='number_of_books',
            field=models.IntegerField(default=1, verbose_name='Количество книг в наличии'),
        ),
        migrations.AlterField(
            model_name='book',
            name='page',
            field=models.IntegerField(default=0, verbose_name='Страницы'),
        ),
        migrations.AlterField(
            model_name='book',
            name='photo',
            field=models.ImageField(upload_to='', verbose_name='Фото обложки'),
        ),
        migrations.AlterField(
            model_name='book',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена (BYN)'),
        ),
        migrations.AlterField(
            model_name='book',
            name='publisher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='references.publisher', verbose_name='Издательство'),
        ),
        migrations.AlterField(
            model_name='book',
            name='rating',
            field=models.IntegerField(default=0, verbose_name='Рейтинг (0 - 10)'),
        ),
        migrations.AlterField(
            model_name='book',
            name='series',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='references.series', verbose_name='Серия'),
        ),
        migrations.AlterField(
            model_name='book',
            name='weight',
            field=models.IntegerField(default=0, verbose_name='Вес книги(гр)'),
        ),
        migrations.AlterField(
            model_name='book',
            name='year',
            field=models.IntegerField(default=0, verbose_name='Год издания'),
        ),
    ]
