# Generated by Django 3.1.2 on 2020-10-19 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20201020_0047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='binding',
            field=models.CharField(max_length=30, verbose_name='Переплет книги'),
        ),
        migrations.AlterField(
            model_name='book',
            name='book_format',
            field=models.CharField(max_length=30, verbose_name='Формат книги'),
        ),
        migrations.AlterField(
            model_name='book',
            name='isbn',
            field=models.CharField(max_length=30, verbose_name='ISBN'),
        ),
        migrations.AlterField(
            model_name='book',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Название книги'),
        ),
    ]
