# Generated by Django 3.1.2 on 2020-10-19 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20201020_0138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='book_format',
            field=models.CharField(max_length=50, verbose_name='Формат книги'),
        ),
    ]
