# Generated by Django 3.1.2 on 2020-11-30 21:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_book_avr_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='avr_rating',
            field=models.SmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
