# Generated by Django 3.1.2 on 2020-11-30 22:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_auto_20201201_0038'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='rating',
        ),
        migrations.AddField(
            model_name='book',
            name='number_of_orders',
            field=models.PositiveIntegerField(default=0, verbose_name='Количество заказазов'),
        ),
        migrations.AlterField(
            model_name='book',
            name='avr_rating',
            field=models.SmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)], verbose_name='Средний рейтинг'),
        ),
    ]
