# Generated by Django 3.1.2 on 2020-10-18 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('references', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Имя автора')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание автора')),
            ],
        ),
    ]
