# Generated by Django 3.1.2 on 2020-10-18 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('references', '0003_series'),
    ]

    operations = [
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Название издательства')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание издательства')),
            ],
        ),
    ]
