# Generated by Django 3.1.2 on 2020-11-22 12:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cart', '0004_bookincart_book'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_status', models.CharField(choices=[('1', 'Заказан'), ('2', 'Собираем заказ'), ('3', 'Доставка'), ('4', 'Доставлен')], default=1, max_length=20, verbose_name='Статус заказа')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Комментарий')),
                ('date_add', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания заказа')),
                ('date_last_change', models.DateTimeField(auto_now=True, verbose_name='Дата последнего изменения заказа')),
                ('cart', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='order', to='cart.cart')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
            },
        ),
    ]
