# Generated by Django 3.1.2 on 2020-11-23 20:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivery_status',
            field=models.CharField(choices=[('1', 'В процессе оформления'), ('2', 'Заказан'), ('3', 'Доставка'), ('4', 'Доставлен')], default=1, max_length=20, verbose_name='Статус заказа'),
        ),
        migrations.CreateModel(
            name='AddressInOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(blank=True, max_length=20, null=True, verbose_name='Страна')),
                ('city', models.CharField(blank=True, max_length=20, null=True, verbose_name='Город')),
                ('index', models.CharField(blank=True, max_length=15, null=True, verbose_name='Индекс')),
                ('address1', models.CharField(blank=True, max_length=50, null=True, verbose_name='Адрес1')),
                ('address2', models.CharField(blank=True, max_length=50, null=True, verbose_name='Адрес2')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='address_in_order', to='order.order')),
            ],
            options={
                'verbose_name': 'Профиль адрес в заказе',
                'verbose_name_plural': 'Профиль адреса в заказах',
            },
        ),
    ]
