# Generated by Django 3.1.2 on 2020-11-23 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_auto_20201123_2312'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='type_of_payment',
            field=models.CharField(default=1, max_length=20, verbose_name='Тип оплаты'),
        ),
    ]
