# Generated by Django 3.1.2 on 2020-11-26 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_order_type_of_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivery_status',
            field=models.CharField(choices=[('1', 'В процессе оформления'), ('2', 'На рассмотрении модерации'), ('3', 'Отменен'), ('4', 'Заказан'), ('5', 'Доставка'), ('6', 'Доставлен')], default=1, max_length=20, verbose_name='Статус заказа'),
        ),
    ]
