# Generated by Django 3.1.2 on 2020-11-17 11:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_auto_20201102_1803'),
        ('cart', '0003_bookincart'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookincart',
            name='book',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='books_in_carts', to='products.book'),
            preserve_default=False,
        ),
    ]
