# Generated by Django 3.1.2 on 2020-12-02 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_bookincart_book'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='coupon_percent',
            field=models.PositiveIntegerField(default=0, verbose_name='Процент скидки %'),
            preserve_default=False,
        ),
    ]
