# Generated by Django 3.1.2 on 2020-12-02 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0005_cart_coupon_percent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='coupon_percent',
            field=models.PositiveIntegerField(default=0, verbose_name='Процент скидки %'),
        ),
    ]
