# Generated by Django 3.1.2 on 2020-11-28 12:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('myauth', '0005_creditcart'),
        ('products', '0007_auto_20201102_1803'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentProducts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(blank=True, default='', null=True, verbose_name='Комментарий')),
                ('date_add', models.DateTimeField(auto_now_add=True, verbose_name='Дата внесения в каталог')),
                ('date_last_change', models.DateTimeField(auto_now=True, verbose_name='Дата последнего изменения карточки')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='comments', to='products.book')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='comments', to='myauth.profile')),
            ],
        ),
    ]
