# Generated by Django 3.1.2 on 2020-11-30 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0002_auto_20201129_0325'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentproducts',
            name='stars',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
