# Generated by Django 3.1.2 on 2020-11-30 21:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0003_commentproducts_stars'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentproducts',
            name='stars',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
